import { LoginResponseDTO } from "../../src/application/use-cases/auth/login/LoginResponseDTO";
import { redisClient } from "../../src/infrastructure/cache/redisClient";
import { app as appNonPersistent, prisma } from "../compositionRootTest";
import { app as appPersistent } from "../../src/compositionRoot"
import request from "supertest";
import { setTimeout } from 'node:timers/promises';


describe("Refresh token endpoints", () => {
    it("should return 201 after succesfully refreshing tokens", async () => {

        //The refreshToken generated by this will persist, but it's acceptable
        const loggedUser = await request(appPersistent).post("/auth/login").send({
            email: "correct.user@mock.com",
            password: "abcd1234",
        });

        const loggedUserReturn: LoginResponseDTO = loggedUser.body;

        await setTimeout(2000);
        //If the setTimeout is not present, the tokenHash wil be equal when tryin to refresh and wil throw an error
        //because there's an unique value repeated

        const response = await request(appNonPersistent).
        post("/auth/refresh").
        auth(loggedUserReturn.refreshToken, { type: "bearer" });

        expect(response.status).toBe(201);
    });

    it("should return 401 if the refreshToken is invalid", async () => {
        const response = await request(appNonPersistent).
        post("/auth/refresh").
        auth("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30", { type: "bearer" });

        expect(response.status).toBe(401);
    })

    afterAll(async () => {
        await prisma.$disconnect();
        await redisClient.quit();
    })
})